Auth e2e tests

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -18,5 +18,10 @@ if [ $? -ne 0 ]; then
   echo "❌ Tests failed. Commit aborted."
   exit 1
 fi
+npm run e2e
+if [ $? -ne 0 ]; then
+  echo "❌ E2E tests failed. Commit aborted."
+  exit 1
+fi
 
 echo "✅ All checks passed. Proceeding with commit."
